"""uniq_lesson

Revision ID: 2fba08aaf981
Revises: 660c85036316
Create Date: 2025-11-15 14:35:24.553192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fba08aaf981'
down_revision: Union[str, None] = '660c85036316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_all_fields', 'lessons', ['time_id', 'day_week', 'type_lesson', 'subject_id', 'teacher_id', 'room_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_all_fields', 'lessons', type_='unique')
    # ### end Alembic commands ###
