"""update_subject

Revision ID: 4b86913fb480
Revises: e5a53e195706
Create Date: 2025-10-23 22:31:56.172620

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b86913fb480"
down_revision: str | None = "e5a53e195706"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subjects", sa.Column("semester", sa.Integer(), nullable=False))
    op.add_column("subjects", sa.Column("total_hours", sa.Integer(), nullable=False))
    op.add_column("subjects", sa.Column("is_optional", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "is_optional")
    op.drop_column("subjects", "total_hours")
    op.drop_column("subjects", "semester")
    # ### end Alembic commands ###
