"""fix_users_role

Revision ID: 4e0c7e52cfef
Revises: 5fc6ab1205b1
Create Date: 2025-11-16 20:09:19.017645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0c7e52cfef'
down_revision: Union[str, None] = '5fc6ab1205b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Text(),
               server_default='user',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Text(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
