"""rename_lessons

Revision ID: 5fc6ab1205b1
Revises: 2fba08aaf981
Create Date: 2025-11-16 19:45:03.366264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc6ab1205b1'
down_revision: Union[str, None] = '2fba08aaf981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('buildings', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('lessons', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('type', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('unique_all_fields'), 'lessons', type_='unique')
    op.create_unique_constraint('unique_all_fields', 'lessons', ['time_id', 'day_of_week', 'type', 'subject_id', 'teacher_id', 'room_id', 'group_id'])
    op.drop_column('lessons', 'type_lesson')
    op.drop_column('lessons', 'day_week')
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('rooms', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using = 'status::boolean',
               existing_nullable=False,
               nullable=False)
    op.add_column('students', sa.Column('middle_name', sa.String(length=100), nullable=False))
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'students', ['phone'])
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('teachers', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('teachers', sa.Column('middle_name', sa.String(length=100), nullable=False))
    op.add_column('teachers', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('teachers', 'name')
    
    ###
    op.create_table(
        'user_id_mapping',
        sa.Column('old_id', sa.Integer(), nullable=False),
        sa.Column('new_id', sa.UUID(), nullable=False)
    )
    op.execute('''
        INSERT INTO user_id_mapping (old_id, new_id)
        SELECT id, gen_random_uuid() FROM users
    ''')
    op.add_column('users', sa.Column('new_id', sa.UUID(), nullable=True))
    op.execute('''
        UPDATE users u 
        SET new_id = um.new_id
        FROM user_id_mapping um 
        WHERE u.id = um.old_id
    ''')
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_column('users', 'id')
    op.alter_column('users', 'new_id', new_column_name='id')
    op.create_primary_key('users_pkey', 'users', ['id'])
    op.drop_table('user_id_mapping')
    ###
    
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using = 'id::uuid',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'middle_name')
    op.drop_column('teachers', 'first_name')
    op.alter_column('subjects', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('students', 'middle_name')
    op.alter_column('rooms', 'status',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('rooms', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('lessons', sa.Column('day_week', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('type_lesson', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_all_fields', 'lessons', type_='unique')
    op.create_unique_constraint(op.f('unique_all_fields'), 'lessons', ['time_id', 'day_week', 'type_lesson', 'subject_id', 'teacher_id', 'room_id', 'group_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('lessons', 'type')
    op.drop_column('lessons', 'day_of_week')
    op.alter_column('groups', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('buildings', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('buildings', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
