"""delete_role

Revision ID: 660c85036316
Revises: d2af34b7d9c8
Create Date: 2025-10-31 00:47:24.800522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "660c85036316"
down_revision: Union[str, None] = "d2af34b7d9c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), server_default="user", nullable=False))
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("users", "role")
    # ### end Alembic commands ###
