"""add 2 fields

Revision ID: 8ba115ac6509
Revises: eb95b09dfba1
Create Date: 2025-10-11 13:54:27.321523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba115ac6509'
down_revision: Union[str, None] = 'eb95b09dfba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('course', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('institute', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'institute')
    op.drop_column('groups', 'course')
    # ### end Alembic commands ###
