"""remove_dateofbirth

Revision ID: 9431c350eb04
Revises: ba3165c249c2
Create Date: 2025-10-25 13:00:56.742078

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9431c350eb04"
down_revision: str | None = "ba3165c249c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "date_of_birth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers", sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
