"""update_teacher_table

Revision ID: ba3165c249c2
Revises: 4b86913fb480
Create Date: 2025-10-24 18:26:15.395495

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba3165c249c2"
down_revision: str | None = "4b86913fb480"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teachers", sa.Column("department", sa.String(), nullable=False))
    op.add_column("teachers", sa.Column("title", sa.String(), nullable=False))
    op.drop_constraint("teachers_name_key", "teachers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("teachers_name_key", "teachers", ["name"])
    op.drop_column("teachers", "title")
    op.drop_column("teachers", "department")
    # ### end Alembic commands ###
