"""cascade-delete

Revision ID: d74628fc8b50
Revises: 9431c350eb04
Create Date: 2025-10-29 18:49:18.892571

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d74628fc8b50"
down_revision: str | None = "9431c350eb04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("rooms_building_id_fkey", "rooms", type_="foreignkey")
    op.create_foreign_key(None, "rooms", "buildings", ["building_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("schedulelessons_room_id_fkey", "schedulelessons", type_="foreignkey")
    op.drop_constraint("schedulelessons_teacher_id_fkey", "schedulelessons", type_="foreignkey")
    op.drop_constraint("schedulelessons_group_id_fkey", "schedulelessons", type_="foreignkey")
    op.drop_constraint("schedulelessons_subject_id_fkey", "schedulelessons", type_="foreignkey")
    op.create_foreign_key(
        None, "schedulelessons", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "schedulelessons", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "schedulelessons", "rooms", ["room_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "schedulelessons", "teachers", ["teacher_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("students", "group_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("students_group_id_fkey", "students", type_="foreignkey")
    op.create_foreign_key(None, "students", "groups", ["group_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="foreignkey")
    op.create_foreign_key("students_group_id_fkey", "students", "groups", ["group_id"], ["id"])
    op.alter_column("students", "group_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "schedulelessons", type_="foreignkey")
    op.drop_constraint(None, "schedulelessons", type_="foreignkey")
    op.drop_constraint(None, "schedulelessons", type_="foreignkey")
    op.drop_constraint(None, "schedulelessons", type_="foreignkey")
    op.create_foreign_key(
        "schedulelessons_subject_id_fkey", "schedulelessons", "subjects", ["subject_id"], ["id"]
    )
    op.create_foreign_key(
        "schedulelessons_group_id_fkey", "schedulelessons", "groups", ["group_id"], ["id"]
    )
    op.create_foreign_key(
        "schedulelessons_teacher_id_fkey", "schedulelessons", "teachers", ["teacher_id"], ["id"]
    )
    op.create_foreign_key(
        "schedulelessons_room_id_fkey", "schedulelessons", "rooms", ["room_id"], ["id"]
    )
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.create_foreign_key("rooms_building_id_fkey", "rooms", "buildings", ["building_id"], ["id"])
    # ### end Alembic commands ###
